dist: xenial
language: python
install:
  - pip install -r requirements.txt --ignore-installed

script:
  - make test

jobs:
  include:
    - stage: test
      script: /bin/true
    - stage: release-edge
      script: make DEFAULT_DOCKER_TAG=edge DOCKER_TAG_VERSION= release-docker
    - stage: release
      script: make release

stages:
  - test
  - name: release-edge
    if: branch = master AND type IS push AND sender = tmacro AND tag IS blank
  - name: release
    if: branch = master AND type IS push AND sender = tmacro AND tag IS present
